name: 'dbt_bigquery_info_schema'
version: '1.0.0'
config-version: 2

profile: 'bigquery_profile'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_bigquery_info_schema:
    +persist_docs:
      relation: True
      columns: True

vars:
  user_timezone_name: 'America/New_York'
