bigquery_profile:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: your-gbq-project-here # TODO (user): change this to your project
      dataset: gbq_info_schema # TODO (user): update this if needed
      threads: 4
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      priority: interactive
